"""fix_reservation_table_id

Revision ID: d9e9116df3b9
Revises: 2000433f35d3
Create Date: 2025-04-15 20:23:45.078890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9e9116df3b9'
down_revision: Union[str, None] = '2000433f35d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('table_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'reservation', 'table', ['table_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.drop_column('reservation', 'table_id')
    # ### end Alembic commands ###
